### ISSUE TITLE
bug(parser): a well-formed modifier-statement error inside a method body misparses into four unrelated diagnostics

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#16377]
Found while fixing #16368 (TS1044 vs TS1184 for a misplaced modifier statement). Separate root cause, separate owner code — not fixed by #16375.

## Repro

```ts
class C { method() { public const z = 1; return z; } }
```

Against pinned `typescript@7.0.2` (`--noEmit --strict --target es2022 --module esnext --pretty false`):

```
tsc:  (1,22): error TS1184: Modifiers cannot appear here.
```

Against tsz `main` (confirmed on unmodified `main`, i.e. this is pre-existing, not introduced by #16375):

```
(1,22): error TS1128: Declaration or statement expected.
(1,35): error TS1248: A class member cannot have the 'const' keyword.
(1,42): error TS1435: Unknown keyword or identifier. Did you mean 'return'?
(1,54): error TS1128: Declaration or statement expected.
```

One clean grammar error becomes four cascading, unrelated ones.

## Root cause

`crates/tsz-parser/src/parser/state_statements.rs:625`, inside `parse_statements`'s error-recovery branch:

```rust
if self.in_block_context()
    && self.in_class_body()
    && matches!(
        self.token(),
        SyntaxKind::PublicKeyword | SyntaxKind::PrivateKeyword | SyntaxKind::ProtectedKeyword
            | SyntaxKind::StaticKeyword | SyntaxKind::AbstractKeyword | SyntaxKind::ReadonlyKeyword
            | SyntaxKind::OverrideKeyword | SyntaxKind::AccessorKeyword
    )
    && self.look_ahead_next_is_identifier_or_keyword_on_same_line()
{
    // emits TS1128 "Declaration or statement expected." and `break`s out of
    // the statement list — i.e. treats the rest of the method body as
    // belonging to the outer class body.
}
```

Per its own comment, this exists for recovery from an **unclosed** `{` inside a class body (e.g. a method body missing its closing brace, where tokens that could start a class member should terminate the inner statement list rather than being consumed as statements). But the condition has no check that a brace is actually missing — it fires on ANY well-formed, syntactically-closed block whenever a modifier-like keyword is followed by an identifier/keyword on the same line, `in_class_body()` being true for the entire class body parse (methods, static blocks, everything nested inside), not scoped to genuine unclosed-brace recovery.

`in_class_body()` is `CONTEXT_FLAG_IN_CLASS`, set once for the whole class-body parse and not cleared per-member (`crates/tsz-parser/src/parser/state_statements_class_declarations.rs`), so it's true inside every method/accessor/static-block body. Any of those bodies containing a legal-looking-but-illegal modifier statement followed by an identifier hits this branch.

## Why it matters beyond the message

`#16375`'s fix for #16368 could not simply set `CONTEXT_FLAG_IN_BLOCK` inside `parse_static_block` (the structurally "correct" fix, since a static block's body is a `Block` in tsc's own AST) specifically because doing so activates this same bug for static blocks. That workaround left `#16375`'s fix narrower and more special-cased than it should be. Fixing this bug properly would let `parse_static_block` set `CONTEXT_FLAG_IN_BLOCK` cleanly.

## Suggested fix shape

Scope the recovery branch to only fire when a close brace genuinely appears to be missing (e.g. only after the statement-list loop has already failed to make progress / hit EOF without finding a matching `}`, or some other unclosed-specific signal), not merely "modifier keyword followed by identifier inside a class body." Needs adjacent cases for the genuine unclosed-brace scenario this heuristic was written for, to make sure that recovery path still works after the guard is added.

## Adjacent cases to check once fixed

- The four modifier keywords `public`/`private`/`protected`/`static`/`override`/`readonly`/`abstract`/`accessor`, each in a method body
- Same shape inside a static block, a getter/setter, and a constructor body
- The genuine unclosed-`{` case this heuristic was meant for (needs a positive regression test to confirm it still recovers correctly)

## Provenance

Machine: cloud
Assistant: claude-code
Model: claude-sonnet-5
Effort: medium
AgentName: ClaudeDE
