### ISSUE TITLE
false-positive(checker): non-strict callback returning `undefined` rejected against `PromiseLike<undefined>` (TS2345, regressed by #16624)

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#16669]
## Summary

Under `strictNullChecks: false`, a callback returning `undefined` is rejected against a parameter expecting `PromiseLike<undefined>`. In non-strict mode `undefined` is assignable to every type, so tsc accepts it.

Regression introduced by #16624 (`1b045bb130`, "QueryCache forwards compiler-option setters to its wrapped TypeInterner"). That PR is **net-positive** on conformance (+2/−1), so this is filed rather than reverted.

## Repro

`TypeScript/tests/cases/compiler/inferenceLimit.ts`, with the fixture's own directives (`// @strict: false`, `// @target: es6`, `// @module: commonjs`):

```
tsc  →  TS2307x1
tsz  →  TS2307x1  TS2345x1        <- the TS2345 is spurious
```

```
error TS2345: Argument of type '(orders: any[]) => undefined' is not assignable to
parameter of type '(value: unknown[]) => PromiseLike<undefined>'.
```

The `TS2307` is expected on both sides (unresolved module in the fixture) and is not part of this issue.

## Structural rule

When `strictNullChecks` is off, `undefined` and `null` are members of every type, so a signature returning `undefined` satisfies any return type — including a generic like `PromiseLike<undefined>`. The return-type relation must consult the *effective* `strictNullChecks` for the compilation being checked.

Given #16624's subject is option forwarding into the interner, the likely shape is that the return-position relation reads a `strictNullChecks` that no longer reflects the non-strict compilation on this path — so it is worth checking whether the setter reaches every consumer, not only the one #16624 targeted.

## Adjacent cases a fix should carry

- non-strict, callback returns `null` rather than `undefined`
- non-strict, non-generic target return type (does the generic matter?)
- **strict** mode: the same shape must still report `TS2345` — this is the negative control that keeps a fix from simply widening
- renamed binders, to keep the decision off any fixture name

## How it surfaced

A conformance **set-difference** against a freshly generated main baseline. The failing count did not move (544 → 544) because other PRs fixed three rows in the same window while this and two others broke — a count comparison scored the whole window as flat.

Machine: m4 · Assistant: claude-code · Model: claude-opus-5[1m] · Effort: high
