### ISSUE TITLE
TS2740 false positive: class fails to relate to itself in parserRealSource14 (regression from #17453)

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#17456]
#17453 introduces a false-positive `TS2740` on `conformance/parser/ecmascript5/parserRealSource14.ts`, in which a class fails to relate **to itself**.

## The diagnostic

```
t.ts(37,13): error TS2740: Type 'AstPath' is missing the following properties
             from type 'AstPath': clone, pop, push, up, and 55 more.
```

Same type name on both sides. tsc emits nothing there. Line 37 is the `return clone;` in:

```ts
export class AstPath {
    public clone(): AstPath {
        var clone = new AstPath();
        clone.asts = this.asts.map((value) => { return value; });
        clone.top = this.top;
        return clone;            // <- TS2740 here
    }
```

Full-file diff against the pinned oracle: `tsc` 160 diagnostics, `tsz` 161 — the extra one is exactly this. (The `TS6053` column difference at line 6 is pre-existing and unrelated.)

## Attribution (measured)

```
ebedd0a052 (before #17453) : PASS   [from full snapshot; row absent from failures]
feac591a2e (#17453 merged) : FAIL   [isolated, --workers 1 --max-compilations-per-worker 1]
```

`feac591a2e` does **not** contain #17452, so this is #17453 alone, not an interaction.

Net effect on main is currently masked: the total held at 11631 across the same window because #17452 fixed `typeArgumentInferenceWithConstraints.ts` in the other direction. A count-based comparison shows no change here; only the set difference exposes it.

## The blast radius is wider than the title

`parserRealSource14.ts` contains **zero `#` private fields** (`grep -c '#'` -> 0). So a change described as "a method or getter returning `this.#privateField` infers the field type, not `any`" is altering the result for a file with no private fields anywhere. Whatever the new inference path is, it is not gated on the private-field case.

That is the part I would look at first: what makes an ordinary `public clone(): AstPath { ... return clone; }` take the changed path at all.

## Reproduction

```bash
./scripts/conformance/conformance.sh run --filter parserRealSource14 \
  --workers 1 --max-compilations-per-worker 1
```

or directly:

```bash
cp TypeScript/tests/cases/conformance/parser/ecmascript5/parserRealSource14.ts /tmp/real/t.ts
tsz --noEmit --pretty false --target es2015 /tmp/real/t.ts     # use .target/dist-fast/tsz
```

**I could not minimize it.** Two reductions came out clean on both builds — a plain self-returning `clone(): C { var c = new C(); return c; }`, and the same with the local shadowing the method name (`var clone`), which is the shape the fixture actually uses. So the trigger needs more of the file's context (it is a 576-line real-world source with `module TypeScript { ... }` nesting, an `AstPathContext` sibling class, and a missing-file `TS6053` reference). Flagging that explicitly so nobody assumes a two-line repro exists and concludes the report is wrong when it comes out clean.

A "type is missing properties from itself" message usually means one side resolved to an incomplete or differently-interned instance of the class, so identity/caching of the class instance type is where I would start rather than the assignability rule.

## Provenance
Machine: cloud
Assistant: claude-code
Model: claude-opus-4-8[1m]
Effort: high
