### ISSUE TITLE
TS1329-vs-TS1238: decorator_has_zero_arg_factory_shape wrongly reports TS1329 for a directly-written zero-param function/arrow decorator expression

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#17123]
Found while running the regression suite for #17122 (a rebase of #17118). Pre-existing on `main`, unrelated to that PR — confirmed via `git stash` that the failure is identical with and without #17122's diff.

`ts1238_es_decorator_zero_arity_factory_emits_error` (`crates/tsz-checker/tests/ts1238_tests.rs`) asserts TS1238 for:

```ts
@(() => {})
class C {}
```

Oracle-verified (`typescript@7.0.2`):

```
case4.ts(1,2): error TS1238: Unable to resolve signature of class decorator when called as an expression.
  The runtime will invoke the decorator with 2 arguments, but the decorator expects 0.
```

tsc reports **TS1238**, not TS1329. But `main`'s `decorator_has_zero_arg_factory_shape` (introduced by #17120, `crates/tsz-checker/src/state/state_checking_members/decorator_signature_checks.rs`) now reports TS1329 instead — the test currently fails with `Expected TS1238 for zero-arity ES class decorator, got: [1329]`.

**Structural rule tsc actually uses**, oracle-verified with adjacent cases:

| decorator expression | shape | tsc |
| --- | --- | --- |
| `@d` where `d` is `function d() { return undefined as any; }` | bare identifier reference to a zero-param function | **TS1329** ("did you mean to call it first and write `@d()`?") |
| `@(() => {})` | directly-written zero-param arrow/function expression | **TS1238** (not-callable-with-2-args), no TS1329 hint |
| `@d()` (same `d` as above) | factory call | no error |

`decorator_has_zero_arg_factory_shape` currently gates only on "every call signature takes zero required params" (`decorator_signature_accepts_no_arguments`), with no check on the *shape of the decorator expression itself*. It needs to also require the decorator expression be a plain identifier or property-access chain (something a user could plausibly have "forgotten to call"), not an inline function/arrow-function literal — mirroring how tsc's own "did you mean to call it first" heuristic only makes sense for a named reference, not an expression written inline at the decorator site.

Owner layer: checker (`decorator_signature_checks.rs` / `class_decorators.rs`, same family as #17108/#17118/#17120).

Repro:
```ts
@(() => {})
class C {}
```
Expected (typescript@7.0.2): `TS1238: Unable to resolve signature of class decorator when called as an expression. The runtime will invoke the decorator with 2 arguments, but the decorator expects 0.`
Actual (tsz, `main`): TS1329.

The existing test `ts1238_es_decorator_zero_arity_factory_emits_error` in `crates/tsz-checker/tests/ts1238_tests.rs` already encodes the correct expected behavior and is currently red on `main` — fixing this should turn it green with no test changes needed.
