### ISSUE TITLE
ts-essentials: Symbol.iterator not found in typeof context

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#5028]
## Summary
The ts-essentials benchmark fails with tsz emitting false positive errors while tsc passes cleanly.

## Reproduction
```bash
# Clone and setup
git clone --depth 1 https://github.com/ts-essentials/ts-essentials.git /tmp/ts-essentials

# Create tsconfig
cat > /tmp/ts-essentials/tsconfig.json << 'TSCONFIG'
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "strict": true,
    "lib": ["es2018"],
    "skipLibCheck": true,
    "noEmit": true
  },
  "include": ["lib/**/*.ts"]
}
TSCONFIG

# tsc passes
npx tsc -p /tmp/ts-essentials/tsconfig.json --noEmit
# (no errors)

# tsz fails
tsz -p /tmp/ts-essentials/tsconfig.json --noEmit
```

## Errors from tsz
```
lib/deep-readonly/index.ts(8,59): error TS2339: Property 'iterator' does not exist on type 'typeof Symbol'.
lib/deep-writable/index.ts(5,60): error TS2339: Property 'iterator' does not exist on type 'typeof Symbol'.
lib/paths/index.ts(90,37): error TS2344: Type 'Type(2488)' does not satisfy the constraint 'Type(2465)'.
```

### Issue 1: Symbol.iterator not found (TS2339)

The failing code in `lib/deep-readonly/index.ts`:
```typescript
type DeepReadonlyObject<Type> = {
  readonly [Key in keyof Type]: Key extends typeof Symbol.iterator  // <-- line 8
    ? Type[Key] extends () => Iterator<infer IteratorType, infer Return, infer Next>
      ? () => Iterator<DeepReadonly<IteratorType>, DeepReadonly<Return>, DeepReadonly<Next>>
      : DeepReadonly<Type[Key]>
    : DeepReadonly<Type[Key]>;
};
```

With `lib: ["es2018"]`, `Symbol.iterator` should be available. A simple test passes:
```typescript
// This works in isolation
type X = typeof Symbol.iterator;
```

But in project-mode with ts-essentials, it fails. This suggests a lib resolution or global scope issue specific to project compilation.

### Issue 2: Type display showing internal IDs (Type(XXXX))

The error `Type 'Type(2488)' does not satisfy the constraint 'Type(2465)'` shows internal type IDs instead of formatted type names. This makes errors unreadable and suggests the type formatter is failing to resolve types.

## Expected Behavior
- tsz should pass ts-essentials with zero errors (matching tsc)
- Error messages should show formatted type names, not `Type(XXXX)` internal IDs

## Environment
- tsz version: 5.9.3
- tsc version: 5.7.2
- ts-essentials: latest main

## Labels
- conformance
- false-positive
- type-display
