### ISSUE TITLE
checker: conformance fingerprint rewrite leaks into user diagnostics

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#4007]
Found at git SHA: acde5ecebc86e84cd8725738010e17b55aa0c338

The checker has source-text fingerprint rewrites that key off literal conformance-test snippets. One of them changes a normal user diagnostic when the source happens to contain the same marker text.

Minimal repro:

```ts
// repro.ts
type A = { c: number };
type constr<Source, Tgt> = Source & Tgt;
declare const q: { [key: string]: A };
q["asd"].b;
```

Commands:

```sh
tsc --noEmit --pretty false repro.ts
/private/tmp/tsz-issue-current-bins/tsz --noEmit --pretty false repro.ts
```

TypeScript reports the alias type:

```text
repro.ts(4,10): error TS2339: Property 'b' does not exist on type 'A'.
```

`tsz` reports a hardcoded structural type that is not the type in this program:

```text
repro.ts(4,10): error TS2339: Property 'b' does not exist on type '{ a: string; }'.
```

The behavior is not limited to a fixture file name. The only trigger is source text containing `type constr<Source, Tgt>` and `q["asd"].b`, so a user file can accidentally enter this branch.

Source-level cause:

`crates/tsz-checker/src/state/state_checking/source_file.rs` calls several post-check diagnostic rewrite helpers from `check_source_file`:

- `rewrite_infer_generic_return_fingerprints`
- `rewrite_intersection_index_signature_fingerprints`
- `rewrite_type_argument_inference_with_constraints_fingerprints`

The repro hits `rewrite_intersection_index_signature_fingerprints` at lines 685-712. It gates on `source_text.contains("type constr<Source, Tgt>")` and `source_text.contains("q[\"asd\"].b")`, then rewrites every nearby TS2339 message exactly equal to `Property 'b' does not exist on type 'A'.` to `Property 'b' does not exist on type '{ a: string; }'.`

That is a conformance-output patch embedded in source checking, not a semantic rule. The surrounding functions use similar literal fixture fingerprints such as `inferFromGenericFunctionReturnTypes3`, `Repros from #5487`, `Breaking change repros from #29478`, and `function someGenerics9<T extends any>`.

Duplicate check:

I searched existing issues for `q["asd"].b`, `{ a: string; }`, and hardcoded checker diagnostics. Issue #3057 covers the separate numeric `Comparable<number>` rewrite, but I did not find an issue for these source-text conformance fingerprint rewrites leaking into user diagnostics.
