### ISSUE TITLE
false-positive(solver): annotated dual-callback `(x:T)=>T` infers `T = <ret> | null` (covariant union) where tsc fixes the contravariant common-subtype — genericCallWithGenericSignatureArguments r2/r3

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#17792]
Split out of #17761 "Point 1" (the r1b first-wins regression from that issue landed in #17791). This is a **separate, pre-existing** inference-resolution defect — reverting #17755 does not change it (confirmed by isolated revert), and it is not a display/restore defect (the relation genuinely uses the wrong `T`).

## Witness (strict)

```ts
declare function foo<T>(a: (x: T) => T, b: (x: T) => T): (x: T) => T;
var r2 = foo((x: Object) => null, (x: string) => "");
```

oracle (`typescript@7.0.2 --strict`):
```
error TS2345: Argument of type '(x: Object) => null' is not assignable to
              parameter of type '(x: string) => string'.
  Type 'null' is not assignable to type 'string'.
```

tsz (`main`):
```
error TS2345: Argument of type '(x: Object) => null' is not assignable to
              parameter of type '(x: string | null) => string | null'.
  Types of parameters 'x' and 'x' are incompatible.
    Type 'string | null' is not assignable to type 'Object'.
      Type 'null' is not assignable to type 'Object'.
```

## Root cause

tsz infers `T = string | null` — it is not a display artifact: the relation checks `string | null` against `Object` (the parameter `x`), so the inferred type is genuinely wrong.

The annotated callback **parameters** (`Object`, `string`) should contribute contravariant candidates; tsc's `getInferredType` prefers the contravariant common-subtype (`string`) when the covariant union (`null | string`) is not assignable to a contra-candidate. In tsz the finalize path is `all_return_type=true` / `direct_param=false` (`generic_call/resolve/finalize`), so `resolve_return_position_inference_type` returns the covariant union of the return contributions and the contra-candidates are never consulted. tsc keeps `T = string`, checks the first callback against `(x: string) => string`, and reports `null` not assignable to `string` in the callback's return.

`r3` (`foo((x: number) => 1, (x: Object) => null)`) reproduces symmetrically (`T = number | null`).

## Owner / fix direction

`generic_call/resolve/finalize` — the return-position finalize (`all_return_type` branch) must consult the concrete contravariant candidates (as the covariant/contra reconciliation in `resolve_covariant_against_contra` already does on the non-`all_return_type` path) before promoting the covariant union. Needs oracle-pinned adjacent cases: `|null`/`|undefined`, renamed binders, reversed argument order (r2 vs r3), and a negative control where the covariant union *is* assignable to a contra-candidate (so the covariant result should stand).

Goal: hold.

**Comment by mohsen1** [comment]
Fixed as a side effect of pr:17795 (merged `b48c993`, filed against #17761's narrowed strict-only residual — same underlying defect, described from the general-assignability angle rather than the generic-call-inference angle).

Root cause matches this issue's own diagnosis exactly: `CompatChecker`'s Object-interface fast path (`crates/tsz-solver/src/relations/compat.rs`) guarded on `TypeId::is_nullable()`, which only matches a bare `NULL`/`UNDEFINED`/`VOID` intrinsic — a union carrying one (`string | null`, the covariant return-position combination this issue traced) fell through the guard and was wrongly accepted as assignable to the `Object`-typed contravariant candidate, so `resolve_covariant_against_contra` never got a chance to prefer the contravariant common subtype. pr:17795 swapped the guard to the union-aware `narrowing::utils::is_nullish_type`; no `generic_call/resolve/finalize` or inference code needed to change.

Verified independently on current `main` (`31a9126`) against both of this issue's witnesses:

```
$ tsz --strict --noEmit r2.ts   # foo((x: Object) => null, (x: string) => '')
error TS2345: Argument of type '(x: Object) => null' is not assignable to parameter of type '(x: string) => string'.
  Type 'null' is not assignable to type 'string'.

$ tsz --strict --noEmit r3.ts   # foo((x: number) => 1, (x: Object) => null)
error TS2345: Argument of type '(x: Object) => null' is not assignable to parameter of type '(x: number) => number'.
  Type 'null' is not assignable to type 'number'.
```

Both byte-match the pinned oracle. Closing as fixed.

---
_Generated by [Claude Code](https://claude.ai/code)_
