### ISSUE TITLE
Missing TS6263: .json resolved through a .d.json.ts companion without --allowArbitraryExtensions (gap after #17019, #17018 closed)

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#17020]
`#17019` made a `.json` specifier prefer its `.d.json.ts` declaration companion —
correct — but tsc only permits that resolution when `--allowArbitraryExtensions`
is set, and reports **TS6263** when it is not. tsz now resolves through the
companion silently, so the diagnostic is missing.

**Unclaimed.** Filing because #17018, which implemented the
`allowArbitraryExtensions` half, was **closed** (it conflicted with #17019 on
`crates/tsz-core/src/module_resolver/file_probing.rs`), so this gate currently
has no owner.

## Repro

```
a/data.json          {"v":1}
a/data.d.json.ts     declare const d: { v: string }; export default d;
a/main.ts            import d from "./data.json"; const s: string = d.v;
tsconfig             { moduleResolution: "bundler", resolveJsonModule: true, strict: true }
                     // NOTE: allowArbitraryExtensions NOT set
```

| | result |
| --- | --- |
| tsc 7.0.2 | `main.ts(1,15): error TS6263: Module './data.json' was resolved to '…/data.d.json.ts', but '--allowArbitraryExtensions' is not set.` |
| tsz `7b0b881563` (pre-#17019) | `TS2322` — companion ignored, `d.v` is `number` |
| tsz `cad666310a` (current main) | **clean** — companion used, no TS6263 |

So the row moved from *wrong diagnostic* to *no diagnostic*. Silence is the worse
direction: tsz now accepts a program tsc rejects, and the resolution it performs
is the one tsc explicitly gates behind a flag.

## Controls (both already correct — the gap is narrow)

| case | tsc | main |
| --- | --- | --- |
| same fixture, `allowArbitraryExtensions: true` | clean | clean ✅ |
| same fixture, **no** `.d.json.ts` companion | TS2322 | TS2322 ✅ |

The second control is the harness check — without a companion both compilers
agree exactly, so the divergence is specific to the companion path, not to JSON
resolution generally.

## Acceptance

- TS6263 at the import specifier when a `.d.json.ts` (or any arbitrary-extension
  declaration) companion is selected and `allowArbitraryExtensions` is unset.
- Both controls above stay unchanged.
- #17018's fixtures are worth salvaging — it was closed for a merge conflict, not
  on merit, and it covered the `allowArbitraryExtensions`-vs-`resolveJsonModule`
  precedence directly.

Machine: m4 / Assistant: claude-code / Model: claude-opus-5[1m] / Effort: high
