### ISSUE TITLE
TS2345 false positive: `window` in an object literal inferred against a union (regression from #17434)

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#17436]
#17434 is a solid net win — it removes three of the four false positives on the core `window` pattern. This issue tracks the one it introduced and the one it left behind. **Not proposing a revert.**

## 1. New false positive: `window` in an object literal inferred against a union

```ts
declare function pick<T>(a: T, b: T, c: T): T;
var r = pick(undefined, { x: 6, z: window }, { x: 6, y: '' });
```

`tsz --noEmit --target es2015 w.ts`

```
tsc 7.0.2        : (clean)
tsz pre-#17434   : (clean)
tsz post-#17434  : w.ts(2,25): error TS2345: Argument of type '{ x: 6; z: Window & typeof globalThis; }'
                   is not assignable to parameter of type
                   '{ x: number; z: Window & typeof globalThis; y?: undefined; } | { z?: undefined; x: number; y: string; } | undefined'.
```

Note the irony: the intersection fast path was added to *remove* spurious assignability failures involving `Window & typeof globalThis`, and here it produces one. The target is a **union** synthesized by inference from the three arguments, and the source is an object literal whose member is the merged surface. The fast path short-circuits when a constituent IS the target or its nominal heritage reaches the target's def — presumably neither holds against a union target, and something in the new early dispatch changes the verdict rather than falling through to the previous path.

### Attribution (measured both directions, isolated)

`conformance/expressions/functionCalls/typeArgumentInferenceWithConstraints.ts` flips on exactly this commit. Run singly with `--workers 1 --max-compilations-per-worker 1` to remove batch-pool state as a variable:

```
1186b1883d (pre-#17434) : PASS  1/1
b9eaf49cc0 (post)       : FAIL  0/1, Fingerprint-only: 1
  TS2345 test.ts:87:36 ... (missing=0, extra=1)
```

`extra=1` — a false positive, not a missing diagnostic.

Full-snapshot confirmation, set-differenced (counts alone were not enough; the same window also contained an unrelated documented −1 from #17428):

```
a91473f3ce : 11630 passed / 413 failing
b9eaf49cc0 : 11628 passed / 415 failing
  newly failing: typeArgumentInferenceWithConstraints.ts   <- this issue
                 inferingFromAny.ts                        <- expected, #17428, documented there
```

## 2. Still-failing case: array-literal element

The PR body lists array-element position as covered, but this still trips the complexity budget:

```ts
const arr: Window[] = [window];
```

```
tsc 7.0.2       : (clean)
tsz post-#17434 : v.ts(2,23): error TS2859: Excessive complexity comparing types 'Window & typeof globalThis' and 'Window'.
```

For contrast, these three **are** fixed by #17434 and are clean on main now (all were errors before it):

```ts
const w: Window = window;   // was TS2859
function take(x: Window) {} // was TS2345
take(window);
```

So the fast path reaches the direct-assignment and argument positions but not the array-literal element position under `--target es2015`. Possibly a difference between this invocation and the PR's own regression test — worth checking which lib/target the covering test uses.

## Suggested test matrix

Whatever fixes the union case should hold all of these together, since each reaches the relation through a different context:

- direct assignment, argument, array element, property, self-reference (the PR's existing positives — keep them green)
- **object literal containing `window`, inferred against a union target** (new, case 1)
- `typeof globalThis` alone must still be rejected from `Window` with TS2741 (the PR's existing negative — must not start passing)

A pass/fail count will not police this: the regression was invisible in the failing **total** because an unrelated row moved the other way in the same window. Use set difference.

## Provenance
Machine: m4
Assistant: claude-code
Model: claude-opus-5[1m]
Effort: high
