### ISSUE TITLE
re-land(checker): switch-chain DP memo + null-exclusion threading (reverted #13083) with temporal.ts guard

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#13388]
## Context
PR #13083 / commit `38221b12ed` (`perf(checker): hoist switch-chain DP memo, finish null-exclusion threading`) was reverted in #13365 because it deterministically regressed `conformance/compiler/temporal.ts`:

```
TS2552 lib.es2021.intl.d.ts:30:47 Cannot find name 'DateTimeFormatPart'. Did you mean 'DateTimeFormat'?
TS2552 lib.esnext.intl.d.ts:24:74 Cannot find name 'DateTimeFormatPart'.
```

Bisect (`e86c754c79..38221b12ed`) pinned `38221b12ed` as the first bad commit; `temporal` passes 1/1 at `644732da3a` and fails at the tip.

## Root cause hypothesis
A flow control-flow DP memo (`crates/tsz-checker/src/flow/control_flow/flow_dp.rs`, +322 lines) returns stale or cross-keyed results, surfacing as corrupted name resolution in lib files. The memo key likely omits part of the narrowing/scope state it caches.

## Re-land requirements
- Identify the exact memo cache-key/invalidation defect (cache-enabled vs cache-disabled runs must agree per ROADMAP rule 5).
- Add `compiler/temporal.ts` as an explicit adjacent regression case, plus a reordered-declaration variant.
- Verify narrowing/switch/controlFlow/discriminant conformance stays 147/147 and `temporal` 1/1 across repeated runs.

Goal: fast (perf re-land); must not regress hold.

**Comment by mohsen1** [comment]
Investigation update: I am dropping active WIP ownership for now because the implementation surface described here appears already present on current `origin/main`.

Findings:
- `flow_dp.rs` and `condition_narrowing.rs` currently match the #13330/#13083 reland shape, including `FlowConditionDpMemos`, `ChainReachabilityMemo`, `resolve_chain_reachability`, and the `chain_reachability_*` tests.
- The current conformance baseline lists `PASS TypeScript/tests/cases/compiler/temporal.ts`.
- The stale `scripts/conformance-last-run.txt` still contains an older `temporal.ts` failure, so I did not close this issue; it still needs a human/CI-backed decision on whether the issue is fully superseded.

I did not open a PR because I could not identify a non-noop code change that would move this issue forward without manufacturing churn. Moving attention to #13397, which is a concrete merge-queue unblocker for landing the active Fast stack.

Provenance: Machine: MacBookPro.fritz.box / Assistant: codex / Model: GPT-5 / Effort: high
