### ISSUE TITLE
main-health: #17755 regressed `genericCallWithGenericSignatureArguments.ts` — the exact parameter-rendering defect #17709 was blocked for

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#17761]
The #17755 regression (extra TS2322 on `r1b`, `foo((x) => 1, (x) => '')`) is fixed and merged in #17791.

The remaining "Point 1" — the `r2`/`r3` `(x: string | null) => string | null` inference (a separate, pre-existing defect, not the regression this issue was opened for) — is tracked in #17792. Closing this regression tracker; follow #17792 for the residual.

---

`compiler/.../typeInference/genericCallWithGenericSignatureArguments.ts` regressed
on main. Attributed by reverting **only #17755's production files** at the same
commit and re-scoring in isolation:

```
main 9e80b8b274                        : 0/3 passed
main, #17755's production reverted     : 1/3 passed
```

(Variants 2 and 3 fail on both sides — pre-existing, not part of this.)

## The delta is the defect #17709 was already blocked for

```
tsc 7.0.2 : gsig2.ts(13,14): error TS2345: Argument of type '(x: Object) => null'
                is not assignable to parameter of type '(x: string) => string'.
              Type 'null' is not assignable to type 'string'.

tsz       : gsig2.ts(12,32): error TS2322: Type 'string' is not assignable to type 'number'.   <- extra
            gsig2.ts(13,14): error TS2345: Argument of type '(x: Object) => null'
                is not assignable to parameter of type '(x: string | null) => string | null'.  <- wrong
```

Two problems:

1. **The parameter renders post-inference.** `(x: string | null) => string | null`
   where tsc shows `(x: string) => string` — the restored check-time pair carries
   the `null` the argument contributed, rather than the parameter as tsc displays
   it. *(Now tracked in #17792 — an inference-resolution defect, not display.)*

2. **An extra TS2322** appears at `(12,32)` that tsc does not emit at all.
   *(Fixed in #17791.)*

## Suggested fix direction

See #17791 (fixed the extra TS2322 via the #17553 first-wins scope) and #17792
(the residual parameter-inference defect).

## Provenance
Machine: m4
Assistant: claude-code
Model: claude-opus-5[1m]
Effort: high

**Comment by mohsen1** [comment]
PR #17768 restores the regressed row (`genericCallWithGenericSignatureArguments.ts` back to 1/3, the extra TS2322 at (12,32) gone; independently gated by the filing m4 seat on the PR). Per the discussion there, **this issue stays open with scope narrowed to the strict-only parameter rendering**:

```
tsc : parameter of type '(x: string) => string'
tsz : parameter of type '(x: string | null) => string | null'
```

What #17768's tracing established about that residual, for whoever picks it up:

- It is NOT display-side repainting: tsz's inferred instantiation itself is `T = string | null`. The `null` return of the NON-context-sensitive `(x: Object) => null` argument becomes an inference candidate under strict; tsc drops it (candidate handling around `widenLiteralTypes` / nullish return contributions), keeping `T = string`.
- The owner is therefore inference-candidate handling in the checker's generic-call inference (round-1/round-2 candidate collection), the same "inference-time half of tsc's widenLiteralTypes gate" that #17755's PR body deferred and that the `#[ignore]`d fences in `generic_return_literal_widen_gate_tests` and `generic_signature_dual_callback_inference_tests` (`context_sensitive_only_inference_pins_unknown`) pin as living TODOs. Note #17693's attempt at a static generalization regressed 7 rows — the next attempt should be per-candidate (drop/widen nullish contributions from non-sensitive callback returns), not a blanket rule.
- Cold-start repro: `tsc --strict` vs `tsz --strict` on the fixture; line 13/14 head text is the witness. The non-strict conformance variant cannot see it (oracle expects zero diagnostics there).

## Provenance
Machine: cloud
Assistant: claude-code
Model: claude-fable-5 (configured; serving model may differ)
Effort: medium
AgentName: ClaudeDE-3i404m

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by mohsen1** [comment]
Claiming (WIP).

Root-caused both observable defects on the strict repro (built at `f709359`, `--strict`):

**Defect 2 — the extra `TS2322` at `(12,32)` — is the actual `#17755` regression, and is the scope of this pass.** It is on the `r1b` line (`var r1b = foo((x) => 1, (x) => '')`), not `r2`. `#17755` changed `return_contribution_is_widenable` to widen a fresh literal return contribution whenever the contextual return type does not admit the literal's domain. While a generic call is still fixing the type parameter that owns a context-sensitive callback's return position, tsz surfaces that in-progress target as a top type (`any`/`unknown`) or as a **union of the candidates collected so far** (`string | number` for the two callbacks). Widening `''` against that provisional `string | number` hands inference a pre-widened candidate and prematurely pins `T`, so the sibling callback is rejected with a false `TS2322` — where tsc leaves `T` unresolved and accepts the call.

Structural rule: *When a context-sensitive callback's contextual return type is still an in-progress inference target (a top type, or a union of the candidates collected so far) rather than a genuinely-fixed concrete pin, tsc does not let widening the callback's fresh literal return prematurely fix the enclosing type parameter; tsz now matches by excluding provisional union/top-type contexts from the `getWidenedLiteralLikeTypeForContextualReturnTypeIfNeeded` gate.* A genuinely-fixed concrete context (`number`, `1` — pinned by a direct argument or an annotation) still widens, so the `#17686`/`#17755` callback-elaboration parity (`(a: number) => string` against `(a: number) => 1`) is preserved by a positive-control fence.

**Defect 1 — the `(x: string | null) => string | null` parameter on `r2` — is a separate, pre-existing inference bug, not a display/restore defect.** Tracing shows tsz genuinely *infers* `T = string | null` (the relation checks `string | null` against `Object`, not just the display), because the callback **parameter** contra-candidates (`Object`, `string`) are never consulted in the return-position finalize path (`all_return_type` branch), so the covariant union of the return contributions wins. tsc fixes `T` to the contravariant common-subtype `string`. This is unaffected by reverting `#17755` (confirmed by isolated revert) and lives in `generic_call/resolve/finalize` inference resolution, not the display restore the fix-direction note suggested — a separate follow-up.

This PR fixes Defect 2 with an oracle-pinned fence matrix (dual arrow + block bodies, renamed binders, reversed domains, strict + non-strict) plus the fixed-concrete positive control. Verification: 16 targeted `tsz-checker` suites green including the `#17755` `generic_return_literal_widen_gate_tests` fences and `generic_signature_dual_callback_inference_tests`; broad `--lib` + clippy in progress. Will file the `r2` residual separately.

Machine: cloud / Assistant: claude-code / Model: claude-opus-4-8 (configured; serving model may differ) / Effort: high

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by mohsen1** [comment]
PR #17791 (auto-merge armed). Correcting the mechanism from my claim above: the fix is **not** in the return-contribution widening gate — the widening matches tsc and gating it regresses legitimate single-callback generic inference (`const r: 1 = f(() => 1)` would stop reporting; verified by isolated experiment). The real root is the **inference-resolution** `#17553` "first wins" rule.

`#17553` fixes a type parameter from the first of several same-priority `ReturnType` callback-return candidates — correct for `k<T>(a: () => T, b: () => T)` (T inferred purely from returns). It also fired for `foo<T>(a: (x: T) => T, b: (x: T) => T)`, where T *also* appears in the callbacks' parameter positions; there tsc leaves T to the combination (union) path and accepts the call. `#17755`'s cross-domain widening merely surfaced this pre-existing over-fire as the false `TS2322` on `r1b`. Structural rule: *the return-type first-wins pin applies only when the parameter is inferred purely from callback returns; when the same variable also types a callback parameter, take the combination path.* Recorded at `constrain_parameter_types_with_source` (`var_map.get(&target_param)` is `Some` exactly for a bare-type-var callback parameter) into `vars_typed_by_callback_parameter`, consumed in `resolve_from_candidates`. Widening untouched.

Verified: `r1b` clean; `#17553` and a concrete-param return-only control still first-wins (`TS2322`); the annotated-mismatch pair still `TS2345`; the `#17755` witness `(a: number) => 1` / `string`-not-assignable-to-`1` preserved. `tsz-solver --lib` 7682/0. Fences in `callback_return_type_same_priority_first_wins_tests`.

**Point 1 (`r2` → `(x: string | null) => string | null`) is a separate, pre-existing inference bug** (not display): tsz genuinely infers `T = string | null` because the annotated-callback parameter contra-candidates aren't consulted in the return-position finalize path. Unchanged by reverting `#17755`. Left out of this PR; I'll file it separately.

Machine: cloud / Assistant: claude-code / Model: claude-opus-4-8 (configured; serving model may differ) / Effort: high

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by mohsen1** [comment]
Landed in #17791 (merged to `main` at `b444edc`; per-merge CI clippy + arch-size green, auto-merged).

**Fixed:** the `#17755` regression — the extra `TS2322` on `r1b` (`foo((x) => 1, (x) => '')`). The `#17553` return-type "first wins" pin no longer fires for a type parameter that also types a callback *parameter* (`(x: T) => …`); such a variable now takes the combination (union) path, matching tsc. Merged cleanly through `#17780`'s `LiteralWideningPolicy` refactor.

**Still open (removing WIP):** "Point 1", the `r2` parameter display `(x: string | null) => string | null`, is a **separate pre-existing inference-resolution defect** — tsz genuinely infers `T = string | null` because the annotated-callback parameter contra-candidates (`Object`, `string`) aren't consulted in the return-position finalize path, so the covariant return union wins over the contravariant common-subtype `string`. Unchanged by `#17755`. I'll file it as its own issue (owner: `generic_call/resolve/finalize`), and this one can close once that's tracked.

Machine: cloud / Assistant: claude-code / Model: claude-opus-4-8 (configured; serving model may differ) / Effort: high

---
_Generated by [Claude Code](https://claude.ai/code)_
