### ISSUE TITLE
fix(checker): object literal argument to generic-constrained param reports TS2345 instead of TS2353 excess-property

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#9728]
## Summary

When a fresh object literal is passed as an argument to a **generic** parameter `T extends C`, tsz reports a plain assignability `TS2345` at the argument span instead of the excess-property `TS2353` at the property span that tsc reports. The non-generic equivalent is handled correctly, so the defect is in excess-property/freshness checking through a generic constraint.

## Minimal repro

```ts
declare function g<T extends { id: number }>(x: T): T;
g({ name: "a" });
```

**tsc** (`--noEmit --strict --target esnext --lib esnext`):
```
n1min.ts(2,5): error TS2353: Object literal may only specify known properties, and 'name' does not exist in type '{ id: number; }'.
```

**tsz** (`--noEmit --strict --pretty false`):
```
n1min.ts(2,3): error TS2345: Argument of type '{ name: string; }' is not assignable to parameter of type '{ id: number; }'.
```

Note both the **code** (TS2353 vs TS2345) and the **span** (2,5 property vs 2,3 argument) differ.

## Expected

`TS2353` at the offending property, matching tsc. The fresh object literal must undergo excess-property checking against the constraint type.

## Boundary / controls

- Non-generic parameter is handled correctly by tsz (proves the freshness machinery exists; the generic path bypasses it):
  ```ts
  declare function g(x: { id: number }): void;
  g({ name: "a" });   // both: TS2353 at (2,5) — correct
  ```
- Object literal that satisfies the constraint with extra props is accepted by both (excess props allowed for generic inference target widening):
  ```ts
  declare function g<T extends { id: number }>(x: T): T;
  g({ id: 1, name: "a" });   // both: clean
  ```

## Root-cause hypothesis + suggested layer

For a fresh object-literal argument to a generic parameter whose constraint is an object type, the checker should run excess-property (freshness) checking against the constraint when the literal lacks/contains properties not present in the constraint, and emit TS2353 at the excess property. tsz appears to route the generic-parameter case straight through the assignability gate (producing TS2345) without the freshness pass that the non-generic path uses. Fix at the checker argument-checking / excess-property orchestration so generic-constrained parameters consult the same freshness gate (lawyer/excess-property policy per CLAUDE.md §5) against the constraint type.

## Adjacent-case test matrix

1. `g<T extends { id: number }>`, literal missing `id` with extra prop (repro) — TS2353 at property.
2. Non-generic `g(x: { id: number })`, same literal — TS2353 (already correct; regression guard).
3. `g<T extends { id: number }>({ id: 1, name: "a" })` — clean (extra prop allowed when constraint satisfied).
4. Renamed type param / constraint props — same behavior (structural).
5. Constraint with optional prop and literal supplying an unknown prop — TS2353.

AgentName: fn-hunter
