### ISSUE TITLE
fix(checker): callback parameters not contextually typed when callee is overloaded (missing TS2339/TS2322)

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#9663]
## Summary

When the called function is **overloaded**, tsz fails to contextually type an arrow-callback's parameters from the resolved overload signature. As a result, type errors inside the callback body (property accesses, assignments) are silently missed. The same code with a single (non-overloaded) signature is checked correctly, so the regression is specific to the overload-resolution path.

## Minimal repro

```ts
declare function on(event: "click", cb: (e: { x: number }) => void): void;
declare function on(event: "key", cb: (e: { code: string }) => void): void;
on("click", e => e.code);
```

**tsc** (`--noEmit --strict --target esnext --lib esnext`):
```
b11min.ts(3,20): error TS2339: Property 'code' does not exist on type '{ x: number; }'.
```

**tsz** (`--noEmit --strict --pretty false`): clean, exit 0 (false negative).

## Expected

`on("click", ...)` resolves to the first overload, so `e` is contextually typed `{ x: number }` and `e.code` must produce TS2339, matching tsc.

## Boundary / controls

Single-signature version IS checked correctly by tsz (proves contextual typing itself works; the overload path is the defect):
```ts
declare function on(event: "click", cb: (e: { x: number }) => void): void;
on("click", e => e.code);   // tsz: TS2339 (correct), matches tsc
```

Selecting the second overload also fails to type the callback (not order-specific):
```ts
declare function on(event: "click", cb: (e: { x: number }) => void): void;
declare function on(event: "key",   cb: (e: { code: string }) => void): void;
on("key", e => e.x);        // tsc: TS2339 on `e.x`; tsz: silent
```

Assignment inside the body is also missed under overloads:
```ts
declare function on(event: "click", cb: (e: { x: number }) => void): void;
declare function on(event: "key",   cb: (e: { code: string }) => void): void;
on("click", (e) => { const z: string = e.x; });  // tsc: TS2322; tsz: silent
```

## Root-cause hypothesis + suggested layer

After overload resolution selects a signature, the checker must establish the chosen signature's parameter types as the contextual type for the corresponding argument expressions before re-checking the arrow bodies. It appears the overload path resolves the call but does not feed the selected signature's parameter types back as contextual types for the callback arguments (whereas the single-signature path does). Fix in the checker call-resolution/contextual-typing orchestration: after picking the overload, re-contextually-type and re-check argument arrow expressions against the selected signature's parameters.

## Adjacent-case test matrix

1. Overloaded `on`, first overload selected, bad property access in callback (repro) — should error TS2339.
2. Overloaded `on`, second overload selected, bad property access — should error TS2339.
3. Overloaded `on`, bad assignment of contextually-typed param inside body — should error TS2322.
4. Single-signature control — already errors correctly (must keep passing).
5. Renamed event literals / property names — same behavior (structural, not name-bound).

AgentName: fn-hunter
