### ISSUE TITLE
9 unit tests failing on main from the 2026-07-28 batch (scoped-gate blind spot, round 2)

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#15983]
All nine verified failing at detached origin/main @ ff739449ec with per-target runs (0/9 pass); baselined at r9 so pushes aren't blocked. Same class as #15969: the batch's per-push gates ran suites scoped to each push's diff, and the full checker+cli+core matrix first ran on the next cross-crate push.

- `tsz-checker::cross_file_recursive_alias_intersection_tests::renamed_binders_member_read_is_clean` — false `TS2339: Property 'body' does not exist on type 'Wrapped<string>'` (cross-file alias-intersection member read)
- `tsz-checker::kysely_callback_context_tests::{imported_conditional_builder_alias_materializes_callback_context, imported_conditional_builder_alias_uses_declaring_file_for_duplicate_helper_names}`
- `tsz-checker::object_assign_identity_tests::builtin_object_assign_reports_nonportable_tagged_template_mapped_alias_default_export`
- `tsz-checker::reexported_symbol_keyed_member_tests::direct_import_symbol_keyed_member_is_clean` — passed after the #15846 revert (132b5880e5), failing again: something in the 07-28 batch re-broke it
- `tsz-cli::driver_tests::cross_file_dependent_operand_aliases_accept_scalars_and_literal_arrays`
- `tsz-cli::evaluator_cache_agreement_tests::branch_filter_agrees_with_conditional_branch_cache_disabled`
- `tsz-core::checker_state_tests::test_class_duplicate_getter_2300`
- `tsz-core::strict_bind_call_apply_tests::strict_bind_call_apply_bind_generic_this_arg_mismatch_uses_ts2769`

Suspect commits (unbisected): the alias-family names sit squarely in #15897 (276e82238e) territory; the TS2300 row near 6c91786286 (duplicate-identifier gathering); the TS2769 row near the overload-anchor landings. Attribution recipe: `CARGO_PROFILE_DEV_DEBUG=0 cargo nextest run -p <pkg> -E 'test(name)'` at detached commits across f97ff4dd79..ff739449ec.

Note: the 3 conformance regressions from the same batch (moduleAugmentationGlobal1/-InAmbientModule5/controlFlowFunctionLikeCircular1) were bisected to #15897 and fixed forward on main; these unit rows remain.

Machine: m4 / Assistant: claude-code / Model: claude-opus-5[1m]

**Comment by mohsen1** [comment]
## Status re-verified on `main` @ `61a2735`: 8 of 9 resolved, 1 remains

Re-ran all nine listed rows on current `main`. Only **one** still fails; the other eight now pass or are legitimately masked:

| row | status on `61a2735` |
| --- | --- |
| `tsz-checker::cross_file_recursive_alias_intersection_tests::renamed_binders_member_read_is_clean` | PASS |
| `tsz-checker::kysely_callback_context_tests::imported_conditional_builder_alias_materializes_callback_context` | PASS |
| `tsz-checker::kysely_callback_context_tests::imported_conditional_builder_alias_uses_declaring_file_for_duplicate_helper_names` | PASS |
| `tsz-checker::object_assign_identity_tests::builtin_object_assign_reports_nonportable_tagged_template_mapped_alias_default_export` | `#[ignore]` — documented harness-only false failure (real `-p tsconfig.json` pipeline is clean in both compilers) |
| `tsz-checker::reexported_symbol_keyed_member_tests::direct_import_symbol_keyed_member_is_clean` | PASS |
| `tsz-cli::driver_tests::cross_file_dependent_operand_aliases_accept_scalars_and_literal_arrays` | **FAIL** |
| `tsz-cli::evaluator_cache_agreement_tests::branch_filter_agrees_with_conditional_branch_cache_disabled` | PASS |
| `tsz-core::checker_state_tests::test_class_duplicate_getter_2300` | PASS |
| `tsz-core::strict_bind_call_apply_tests::strict_bind_call_apply_bind_generic_this_arg_mismatch_uses_ts2769` | PASS |

## The remaining failure is a #15396 materialize-or-defer witness, not array-literal-recovery

The test name suggested "literal-array recovery," but the failure is broader and its root is the unmaterialized cross-file alias constraint. The extra diagnostic is a false positive on the **valid** `['one','two']` operand (`string[]` not assignable to `DependentOperand<Registry, keyof Registry, "category">`), while tsc accepts it.

Minimized to a 6-file graph where even a **scalar** valid operand fails (so this is not array-specific):

```ts
// use.ts — column/expression/reference/value/api.ts unchanged from the test fixture
import type { Filter } from './api.js'
interface RegistryRow { title: string; category: 'one' | 'two' | 'three' | 'four' }
interface Registry { entries: RegistryRow }
declare const f: Filter<Registry, 'entries'>
f.where('category', 'in', 'one')   // tsz: false TS2345; tsc: clean
```

`where<Ref, Value extends DependentOperand<DB, TB, Ref>>` checks the operand against the *constraint* `DependentOperand<DB, TB, Ref>`, but at the relation site that constraint is still the unreduced cross-file alias `Application` (`DependentOperand<Registry, keyof Registry, "category">` — note `TB` never collapses to `"entries"`, and the whole `InputValueOrList → InputValue → FieldOutput → RawFieldOutput` mapped/indexed/conditional chain is never materialized). `'one'` — and `['one','two']` widened to `string[]` — are then judged against an unmaterialized operand and rejected. This is the exact failure mode #15396 describes ("decision sites judge unmaterialized `Lazy`/`Application` operands"), so the fix belongs to that campaign rather than to a local patch in the call path.

Verified: `.target/debug/tsz` vs `tsc` 6.0.2, `--strict --skipLibCheck --target es2022 --module esnext --moduleResolution bundler`; `generic_call::resolve::finalize` trace confirms the operand reaches the constraint check already widened while the constraint stays an unreduced `DependentOperand` application.

Machine: cloud / Assistant: claude-code

---
_Generated by [Claude Code](https://claude.ai/code)_
