### ISSUE TITLE
regression(solver): #17618 adds 5 false-positive TS2416 on the zod required row (conformance-invisible)

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#17630]
Goal: green

## Summary

#17618 introduced **5 false-positive TS2416** on the `zod` **required**
benchmark row. Bisected to `df6398c2fd` on the real fixture at its pinned ref
(`93b0b6892cc0`), using the guard's own tsconfig and the **pinned 7.0.2**
oracle.

```
oracle 7.0.2            : 0 diagnostics (zod compiles clean)

4b68c45bff (before #17618): 2
    src/types.ts(2009,37) TS2349      <- #16055
    src/types.ts(2434,7)  TS2322      <- #17586

df6398c2fd (#17618)       : 7
    src/types.ts(2009,37) TS2349
    src/types.ts(2213,3)  TS2416      <- NEW
    src/types.ts(2363,3)  TS2416      <- NEW
    src/types.ts(2434,7)  TS2322
    src/types.ts(2475,3)  TS2416      <- NEW
    src/types.ts(2575,3)  TS2416      <- NEW
    src/types.ts(2671,3)  TS2416      <- NEW
```

Adjacent commits are clean, so the attribution is unambiguous: `dbeb193084` = 2,
`4b68c45bff` (which adds #17617/#17621/#17619) = 2, `df6398c2fd` = 7.

## The false positive

```
src/types.ts(2213,3): error TS2416: Property '_parse' in type 'ZodTuple<T, Rest>'
  is not assignable to the same property in base type
  'ZodType<OutputTypeOfTupleWithRest<T, Rest>, ZodTupleDef<T, Rest>, InputTypeOfTupleWithRest<T, Rest>>'.
    Type '(ctx: ParseContext, data: any, parsedType: ...) => ParseReturnType<any>'
      is not assignable to type
    '(_ctx: ParseContext, _data: any, _parsedType: ...) => ParseReturnType<OutputTypeOfTupleWithRest<T, Rest>>'.
```

Every one is the same shape: a subclass `_parse` override checked against the
`ZodType` base, where the return `ParseReturnType<any>` no longer relates to
`ParseReturnType<Concrete>`. That is consistent with #17618's change — it made
the variance accept path stricter, and `any`-returning overrides are exactly
what a general variance measurement used to let through.

## Why nothing caught it

**Conformance is neutral for #17618** — I re-verified 11658 with an empty set
difference after the narrowing landed, and that is still true. The 12,043-case
suite simply has no row exercising this shape, so a green conformance delta says
nothing about it.

The repo contract already anticipates this ("project-corpus smoke when a
required row may be affected"), and I did not run it: I gated #17618 on
conformance plus its own unit tests and stopped there. A solver **relations**
change against a row family described as "recursive conditionals, object guards,
class/generic identity" is precisely the case that needs the corpus smoke. My
miss, and the reason this surfaced a day late.

## Suggested next step

The pre-#17618 behaviour accepted these overrides, matching tsc. The narrowing
in `a5e6705073` fixed the conformance rows I originally blocked on
(`varianceMeasurement.ts`, `mappedTypeErrors.ts` — both verified passing on
merged main), so the remaining over-restriction is narrower than the original
but still real. Whoever picks this up: the accept path needs to keep admitting
an `any`-returning override against a concrete base return.

Reproduce in ~5 minutes:

```bash
git clone --depth 1 https://github.com/colinhacks/zod.git /tmp/zodfx
cd /tmp/zodfx && git fetch --depth 1 origin 93b0b6892cc0cfee8d0bec4e2e1242c7df771f95 \
  && git checkout --detach 93b0b6892cc0cfee8d0bec4e2e1242c7df771f95
# write the guard's tsconfig (tsz_write_zod_config in scripts/bench/project-fixtures.sh)
tsz --project tsconfig.flat.json --pretty false
```

## Provenance
Machine: m4
Assistant: claude-code
Model: claude-opus-5[1m]
Effort: high
