### ISSUE TITLE
main-health: #17769 broke `callback_return_site_widens_type_argument` — literal preservation collides with an existing widening fence

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#17773]
Main (`fc1541872a`) is red in the checker lib lane:

```
cargo nextest run -p tsz-checker --lib
  11721 run, 11720 passed, 1 failed
  conditional_never_param_inference_tests::callback_return_site_widens_type_argument
```

## Attributed to #17769

Reverting its single production file
(`crates/tsz-solver/src/operations/generic_call/normalization.rs`) at the same
commit makes the test pass:

```
main as-is                        : FAIL
main, #17769's production reverted : PASS
```

The opposition is right there in the names: #17769 is "**keep the literal** a
contextual type pins on a generic call's return parameter"; the fence is
"callback return site **widens** type argument". Both cannot hold for the same
shape, so one of them is wrong about tsc — that is the question to settle before
picking a fix.

The fence is old — it dates to #9962 ("preserve inferred literal type args at
return top level, reduce conditional/never params"), so it is not a fresh
expectation. Worth running its source through the pinned 7.0.2 oracle first:
today produced two fences that asserted the *opposite* of tsc (#17689, #17707),
so "the old fence must be right" is not safe either.

## How it reached main

This is a **semantic merge conflict**, not a bad PR in isolation:

```
my gate tree for #17763 (= #17763 + main at 22:35) : test PASSED, lane 11721/11721
main after #17769 merged                            : test FAILS
```

#17769 and #17763 were each green against the main they were measured on;
#17769 landed in the window between my gate and #17763's merge. Neither author
could have seen it, and the per-merge lane (`clippy` + `arch-size`) does not run
the checker lib lane where the fence lives.

#17769 also went from draft to merged inside that window, so it was never gated —
the same path #17755 took to produce #17761 earlier today.

Reproduce:

```bash
cargo nextest run -p tsz-checker --lib -E 'test(callback_return_site_widens_type_argument)'
```

Runs in 0.04s.

## Provenance
Machine: m4
Assistant: claude-code
Model: claude-opus-5[1m]
Effort: high

**Comment by mohsen1** [comment]
Oracle-checked the contested fence. **tsc disagrees with both sides**, and the
actual failure is a *duplicate*, not a widening disagreement.

## What tsc really does

```ts
declare function h<U>(fn: () => U, init: U): U;
const r: 5 = h(() => 5, 0);
```

```
tsc 7.0.2 : w.ts(2,7): error TS2322: Type '0 | 5' is not assignable to type '5'.
              Type '0' is not assignable to type '5'.
            (exactly 1 TS2322)
```

`U` infers to **`0 | 5`** — the union of both inference sites — *not* `number`.
So the fence's own comment is wrong about the mechanism:

> U is inferred from a callback return position, so the literal `5` widens to
> `number`

tsc does not widen here. The fence's *assertion* is only
`count(TS2322) == 1`, which matches tsc, so the fence is right for the wrong
stated reason. That is worth fixing in the comment regardless of how this issue
is resolved — a misleading rationale on a fence sends the next person the wrong
way, exactly as #17707's `..._no_2403` name did today.

## The actual failure is an over-report

```
harness (check_source_diagnostics) on main : 2 TS2322   <- fence asserts 1
tsz CLI, same source                       : 1 TS2322   ('number' is not assignable to '5')
tsc 7.0.2                                  : 1 TS2322   ('0 | 5' is not assignable to '5')
```

So #17769 did not flip a widening decision the fence guards — it introduced a
**duplicate diagnostic** on this shape, visible through the harness. The CLI
emits one (with the wrong type rendered, `number` rather than `0 | 5` — a
pre-existing, separate inaccuracy).

Two things to fix, then:

1. **The duplicate** (#17769's regression) — the fence catches it and should stay.
2. **The rendering**, pre-existing on both sides: tsz says `number` where tsc says
   `0 | 5`. Not this issue's scope, but worth its own note since the fence's
   comment currently enshrines the wrong behavior as intended.

Correcting my framing in the issue body: I described this as "both cannot hold
for the same shape, so one of them is wrong about tsc." That was the wrong
dichotomy — the fence's count is right, its explanation is wrong, and the
regression is a duplicate rather than a widening flip.

## Provenance
Machine: m4
Assistant: claude-code
Model: claude-opus-5[1m]
Effort: high

**Comment by mohsen1** [comment]
Claiming this — main has been red on it for ~40 minutes and PRs are merging on top. Diagnosis is in the comment above: #17769 introduced a duplicate TS2322 (harness sees 2, tsc and the CLI see 1). Starting from `normalization.rs`.

## Provenance
Machine: m4
Assistant: claude-code
Model: claude-opus-5[1m]
Effort: high

**Comment by mohsen1** [comment]
**Correcting my comment above — these are not duplicate diagnostics, and the fix I implied would be wrong.**

Printing the two TS2322s (offset, length, text) instead of just counting them:

```
(55, 1, "Type '0' is not assignable to type '5'.")   <- the declared name `r`
(70, 1, "Type '5' is not assignable to type '0'.")   <- the literal `5` in `() => 5`
```

Different anchors, different messages, opposite directions. tsz is fixing `U = 0` from `init`, then rejecting the callback's `5` against it. That is a second, genuinely distinct error — not one error reported twice.

## What tsc actually does

Probing the inferred `U` directly (assign to `null` and read the reported source type), holding the call `h(() => 5, 0)` fixed and varying only the contextual type:

| probe | contextual type | inferred `U` |
| --- | --- | --- |
| `const a: 5 = h(() => 5, 0)` | `5` (literal) | **`0 \| 5`** |
| `const b = h(() => 5, 0)` | none | `number` |
| `const c: number = h(() => 5, 0)` | `number` | `number` |
| `const d = h(() => 5, 5)` | none | `number` |
| `const e = g(0)` (`g<U>(init: U): U`) | none | `0` |

The union appears only under a **literal** contextual type. That is `getCovariantInference`: the contextual type seeds a `ReturnType`-priority inference, and `InferencePriority.PriorityImpliesCombination` (`ReturnType | MappedTypeConstraint | LiteralKeyof`) selects

```ts
getUnionType(baseCandidates, UnionReduction.Subtype)   // not getCommonSupertype(baseCandidates)
```

## Structural rule

When a generic call's result is checked against a literal contextual type and the type parameter occurs at top level of the return type, tsc seeds a `ReturnType`-priority inference from that contextual type, which both (a) suppresses literal widening of the candidates and (b) combines **all** candidates into a union.

#17769 implemented (a) without (b). With a single candidate the two are indistinguishable, which is why its own fences pass; with two conflicting candidates tsz picks one (`0`) and then reports a spurious error at the other inference site.

## What that means for this fence

The fence's assertion of `1` was right for the wrong reason, and its comment is wrong in both worlds:

```
tsc 7.0.2        U = 0 | 5     1 diagnostic, at `r`:  Type '0 | 5' is not assignable to type '5'.
tsz pre-#17769   U = number    1 diagnostic, at `r`:  Type 'number' is not assignable to type '5'.
tsz post-#17769  U = 0         2 diagnostics
```

So tsz has never matched tsc here. The count matched before by coincidence. Restoring green by reverting only recovers the coincidence — worth doing to unblock main if a real fix is not imminent, but it should not be recorded as parity, and this fence should be re-pinned on the message text (`'0 | 5'`), not just the count. A count-only fence cannot tell these three worlds apart.

Owner: solver inference (`operations/generic_call`), candidate resolution — not the widening gate alone.

## Provenance
Machine: m4
Assistant: claude-code
Model: claude-opus-5[1m]
Effort: high

**Comment by mohsen1** [comment]
**Narrowing my own claim above:** the empirical table stands, the *mechanism* attribution does not.

I attributed the union to `InferencePriority.PriorityImpliesCombination` by reading `TypeScript/src/compiler/checker.ts`. That file is the stale 6.0 corpus, not the 7.0.2 oracle this repo pins — and its formula does not reproduce my own probes:

```
widenLiteralTypes = !primitiveConstraint && inference.topLevel
                    && (inference.isFixed || !isTypeParameterAtTopLevelInReturnType(sig, tp))
```

For probe B (`const b = h(() => 5, 0)`) and probe E (`const e = g(0)`), `U` occurs at top level of the return type and is not fixed, so this predicts *no widening for either*. Observed: B = `number`, E = `0`. So whatever 7.0.2 does here, it is not this formula, and `PriorityImpliesCombination` is not established as the cause. A second candidate mechanism that fits at least as well is `literalTypesWithSameBaseType` inside `getCommonSupertype` (both `0` and `5` are number literals), but I have not confirmed that either.

What is measured and reliable is only the behavior table:

| contextual type | inferred `U` |
| --- | --- |
| `5` (literal) | `0 \| 5` |
| none | `number` |
| `number` | `number` |

and the three-way comparison showing tsz has never matched tsc on this fence. Anyone fixing this should derive the rule from the 7.0.2 binary and tsgo's `checker.go`, not from the submodule's `checker.ts`.

## Provenance
Machine: m4
Assistant: claude-code
Model: claude-opus-5[1m]
Effort: high

**Comment by mohsen1** [comment]
**Regression fixed, `main` is green again — leaving this open for the underlying gap.**

#17778 landed as `f88b9d21`. `cargo nextest run -p tsz-checker --lib` on merged `main`: **11730/11730 pass** (was 11720/11721 with `callback_return_site_widens_type_argument` red). Conformance was verified as a set difference between two runs at asserted SHAs — merge-base `4029bc3127` and branch `a16b35bcee`, both 11666/377 — with **0 newly failing and 0 newly passing**.

What #17778 fixed is the *spurious second diagnostic*: the contextual-literal pin now applies only while the fresh literal candidates agree, which is the space #17769's own fences occupy.

What remains open, and why this issue stays open:

```
tsc 7.0.2   U = 0 | 5     Type '0 | 5' is not assignable to type '5'.
tsz         U = number    Type 'number' is not assignable to type '5'.
```

tsz still does not **combine** candidates under a literal contextual type — it widens instead. The diagnostic count now matches, the type text does not. Note tsz has never matched tsc on this witness; before #17769 the count matched by coincidence, which is why the fence is now pinned on message text rather than count alone.

Anyone picking this up: derive the rule from the 7.0.2 binary and tsgo's `checker.go`, not the submodule's `checker.ts` — as noted above, the 6.0 `widenLiteralTypes` formula does not reproduce the observed probes.

## Provenance
Machine: m4
Assistant: claude-code
Model: claude-opus-5[1m]
Effort: high

**Comment by mohsen1** [comment]
Claiming the open residual (WIP) — the candidate-**combination** gap, per the explicit handoff above. #17778 closed the spurious-second-diagnostic regression; what remains is that under a literal contextual pin tsz **widens** disagreeing fresh literal candidates to their common base instead of **combining** them into a union:

```ts
declare function h<U>(fn: () => U, init: U): U;
const r: 5 = h(() => 5, 0);
```
- tsc 7.0.2: `U = 0 | 5` → `Type '0 | 5' is not assignable to type '5'.`
- tsz: `U = number` → `Type 'number' is not assignable to type '5'.`

Structural rule (per the oracle probe table in the thread): `When a generic call's result is checked against a literal contextual type and the type parameter occurs at top level of the return type, tsc seeds a ReturnType-priority inference that both (a) suppresses literal widening of the candidates AND (b) combines all candidates via getUnionType(..., UnionReduction.Subtype); tsz currently does (a) only.` The union appears only under a literal contextual type (no-context stays `number`), so the fix is gated on the existing `contextual_return_type_pins_literal` classifier — no change to the no-context / concrete-context paths.

Plan: extend the contextual-literal-pin path in the full inference engine to union the fresh literal candidates for the marked (top-level-in-return, unfixed) variable instead of taking the common supertype; re-pin the fence on the message text (`'0 | 5'`) rather than count-only; adjacent matrix (renamed binders, `|null`, multi-candidate agree vs disagree, no-context negative control); verify witness → `0 | 5`, `cargo nextest run -p tsz-checker --lib` green, conformance snapshot neutral, emit floors held.

Provenance — Machine: cloud · Assistant: claude-code · Model: claude-opus-4-8[1m] (configured; serving model may differ) · Effort: high

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by mohsen1** [comment]
Resolved by #17784 (merged to `main` as `1711dc4`).

The fence broke because `#17769` preserved the literal a contextual type pins but tsz had no *combination*, so it kept `U := 0` and re-rejected the callback's `5` (the spurious second TS2322). `#17778` then widened the disagreeing pinned literal to `number` — right diagnostic count, wrong inferred type — and explicitly deferred the real fix here.

#17784 does the combination: when a call pins a naked top-level-in-return type parameter to a literal and its argument-derived covariant candidates are all fresh literals of one base type, `resolve_from_candidates` unions them (`tsc`'s `getSupertypeOrUnion`), so `const r: 5 = h(() => 5, 0)` infers `U = 0 | 5` and reports exactly one TS2322 — matching `tsc` 7.0.2 in both count and rendered type. The fence now asserts the `'0 | 5'` text rather than `'number'`.

It composes with `#17780`: the union keys on the contextual mark only (`skip_literal_widening`), running before the pin-agreement narrowing, so a return-position-only preserve with no contextual literal (`const b = h(() => 5, 0)`, tsc `number`) is untouched.

Verification (merged tree): checker `--lib` 0 failures, solver `--lib` 7684/0, conformance +1 / 0 regressions (`typeArgumentInferenceWithObjectLiteral.ts` now passes), CI fast lane green.

The remaining `annotated_callback_literal_survives_without_context` gate row (annotated callback, return-position preserve without a contextual type) is a separate residual pre-existing on `main` — orthogonal to this fence and not part of this issue.

---
_Generated by [Claude Code](https://claude.ai/code)_
