### ISSUE TITLE
regression(checker): TS2416 FP on ZodNativeEnum._parse override — #15840 re-broke the Zod required row (bisected)

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#15883]
Goal: green

## Regression
The Zod required row went GREEN on 2026-07-20 (published @ 68ca432740, tsz exit+diagnostics matching tsc) and is RED again from 2026-07-21 onward. Bisected across the 68ca432740..0d6c5dd476 window with the zod fixture as the oracle: **first bad commit is 2a296929cb — 'fix(checker): align overloaded conditional return variance (#15840)'** (class_implements_checker/core.rs + query_boundaries/class.rs + the recursive overload-return-veto change in solver).

## Witness (still fires at main tip 57940bc58a, exactly 1 diagnostic)
```
.target-bench/external/zod/src/types.ts(3012,3): error TS2416: Property '_parse' in type 'ZodNativeEnum<T>' is not assignable to the same property in base type 'ZodType<T[keyof T], ZodNativeEnumDef<T>, Output>'.
  Type '(ctx: ParseContext, data: any, _parsedType: ...) => ParseReturnType<T[keyof T]>' is not assignable to type '(_ctx: ParseContext, _data: any, _parsedType: ...) => ParseReturnType<T[keyof T]>'.
```
tsc 6.0.3: clean. The two rendered signatures differ only in parameter NAMES — the failing relation is `ParseReturnType<T[keyof T]>` vs itself (a conditional-type application), i.e. the new overload-conditional-return variance path fails identity/subtype on the same application rather than a real shape difference. Note #15840's own fix targeted overloaded conditional returns; ZodType._parse is a single (non-overloaded) method whose return is the conditional alias ParseReturnType — likely the new veto/variance path over-applies to the non-overloaded case.

## Repro
`scripts/bench/bench-vs-tsgo.sh --prepare-only` once, then `tsz --noEmit -p .target-bench/external/zod/tsconfig.flat.json` (renamed-binder adjacent case: the same shape reduces to a ~20-line ZodType/ZodNativeEnum skeleton with an abstract method returning a conditional alias parameterized by T[keyof T]).

## Impact
Required-row Green count drops 10 -> 9; today's published benchmark data carries Zod red again (honest state). Roadmap Goal-1 blocker.

## Provenance
Machine: m1
Assistant: claude-code
Model: claude-fable-5
Effort: max
AgentName: M1FableArchitect
