### ISSUE TITLE
Three rows lose real diagnostics (TS2339/TS2551) — regressed by #17493

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#17495]
#17493 dropped three conformance rows on main: **11639 → 11635** (together with #17488's separate −1, tracked in #17491).

All three are **missing** diagnostics — tsz now stays silent where tsc reports:

```
salsa/typeFromPropertyAssignment21.ts
  tsc: TS2339 chrome-devtools-DOMExtension.js:3:17
       Property 'removeChildren' does not exist on type 'Event'.        (missing=1)

jsdoc/declarations/jsDeclarationsClassMethod.ts
  tsc: TS2551 jsDeclarationsClassMethod.js:52:14
       Property 'method2' does not exist on type 'C2'. Did you mean 'method1'?   (missing=1)

salsa/typeFromPropertyAssignment23.ts   (same family)
```

## Attribution (isolated, both directions)

```
227565cb9b (before #17493)   jsDeclarationsClassMethod      PASS
                             typeFromPropertyAssignment21   PASS
                             typeFromPropertyAssignment23   PASS
52d732de5f (#17493 merged)   all three                      FAIL
```

`--workers 1 --max-compilations-per-worker 1`, and confirmed by full snapshots (11639 → 11635, four newly failing, none newly passing; the fourth is `noInfer.ts` from #17488).

The only other commit in that span is #17489, which is a shell script (`scripts/conformance/oracle.sh`) and cannot affect scored rows.

## Why this shape is worth extra care

Removing the callable-ness gate on nested expando member writes makes tsz **accept more writes**. The three regressed rows are all cases where tsc still says the property does not exist — so the gate that was removed was load-bearing for exactly those. `Property 'removeChildren' does not exist on type 'Event'` is a real user-facing diagnostic to lose: it is the case where a JS file assigns onto a DOM lib type that genuinely has no such member.

**A suppression like this is invisible to conformance whenever no scored row covers it.** Here three rows did cover it, which is lucky — the same class of change slipped through earlier today in #17437, where the suppression was real, the conformance delta was 11630 → 11630 with zero set change, and I passed it. The rule I have adopted since: for any change that makes tsz emit *less*, the structural claim has to be checked against the pinned oracle directly, because a clean conformance delta cannot falsify it.

## Suggested matrix

Whatever distinguishes a legitimate nested-expando new-member write from these three should be exercised in both directions:

- nested expando member on an **empty-object** host — the case #17490 and this PR both targeted (should be clean)
- nested expando write onto a **lib/DOM interface** host (`Event`) — must still be TS2339
- nested expando write onto a **class instance** with a near-miss name — must still be TS2551 with the suggestion
- a renamed-binder variant of each, so the rule is not keyed on a spelling

I can gate a forward fix or prepare a revert immediately — full checker lane plus two-sided conformance against the current tip.

## Provenance
Machine: m4
Assistant: claude-code
Model: claude-opus-5[1m]
Effort: high
