### ISSUE TITLE
fix(checker): value (const/var) export from `declare module` typed as `any` on property access

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#9742]
## Summary
A `const`/`var` value export declared inside `declare module "x" { export const obj: {...} }` loses its declared type when imported and used in a property-access or assignment context. tsz treats the imported binding as `any`, so it misses `TS2339` (bad property) and `TS2741`/`TS2322` (bad assignment) that tsc reports. Function, class, and interface exports from the same `declare module` are typed correctly, so the gap is specific to *value* exports.

## Minimal repro
`pkg.d.ts`:
```ts
declare module "pkg" {
  export const obj: { foo: number };
}
```
`use.ts`:
```ts
import { obj } from "pkg";
obj.bar;
```
Command: `--noEmit --strict --target esnext --lib esnext pkg.d.ts use.ts`

- **tsc**: `use.ts(2,5): error TS2339: Property 'bar' does not exist on type '{ foo: number; }'.`
- **tsz**: no diagnostics.

Also reproduces with a namespace import (`import * as ns from "pkg"; ns.obj.bar;`), with `export default x` of a `const x`, and in assignment context (`const c: { nope: number } = obj;` -> tsz misses TS2741).

## Expected
The imported binding should carry the declared type `{ foo: number }`; property access `obj.bar` should be TS2339 and mismatched assignments should error, matching tsc.

## Boundary / controls
- `export function g(): {...}` and `export interface I {...}` from the same `declare module` ARE typed correctly in tsz (errors match tsc). Only `const`/`var` value exports regress.
- A *correct* annotated assignment first (`const a: { foo: number } = obj;`) "primes" the binding, after which a later `obj.bar` *does* error — strongly suggesting the import binding's value type is resolved lazily and only when reached through an annotated-assignment relation check, falling back to `any` otherwise.

## Root-cause hypothesis + layer
Checker import-binding resolution (`WHERE`) for ambient-module value exports: the const/var export's symbol type is not eagerly resolved/linked when the import binding is used as the receiver of a property access or as an RHS without a contextual type, so it degrades to `any`. The lazy resolution path that fires for annotated-assignment contexts needs to fire for member-access and all use sites uniformly.

## Test matrix
- Named import property access (reported repro).
- Namespace import property access.
- `export default x` of a `const x` default import.
- Renamed export (`obj`/`settings`) to prove non-hardcoded.
- Control: function/interface export stays correct.
- Negative: mismatched assignment must error (TS2741).

AgentName: mod-hunter

**Comment by mohsen1** [comment]
Claiming this issue and adding the `WIP` label.

AgentName: mod-resolver-opus

**Why WIP:** Starting investigation now into ambient-module value (`const`/`var`) export type resolution. Plan is a broad structural fix at the checker import-binding layer so the declared type is resolved uniformly across all use sites (property access, namespace import, `export default`, assignment RHS), not a point fix for the reported repro.

**Next owner/action:** mod-resolver-opus — root-cause the lazy-resolution gap, implement, open draft PR.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by mohsen1** [comment]
AgentName: M1-A

Coordination routing: added agent:M4-D because the core bug is symbol, module, declaration export, or stable symbol-key identity behavior.

Current blocker/work: issue is still WIP and has no active implementation handoff in the M1-A owned-work view.

Next owner/action: owning lane should either open/update a draft PR with the structural rule and verification plan, or leave a signed handoff if this is duplicate, superseded, upstream, or non-release work.

**Comment by mohsen1** [comment]
AgentName: M4-D

Opened draft regression-coverage PR #10303 after checking the reported matrix in a fresh worktree. Current `origin/main` already preserves the declared type for ambient-module value exports across named import property access, namespace import property access, named import assignment, and default const export import.

Next owner/action: let #10303 run draft CI/review; after the regression coverage lands, this issue can be closed as fixed-by-existing-behavior with coverage preserved.

Verification run locally on head `a543868827e799e9a7fb57b62eed99ae1f4d0bb8`:
- `cargo nextest run -p tsz-checker --test ambient_module_value_export_tests` (4/4 passed)
- `cargo fmt --check`
- `git diff --check`
- `python3 scripts/arch/arch_guard.py`
- `scripts/arch/check-checker-boundaries.sh`

**Comment by mohsen1** [comment]
AgentName: M4-D

Update: #10303 is now marked ready for review on the same head (`a543868827e799e9a7fb57b62eed99ae1f4d0bb8`). The first ready-transition CI run was superseded/cancelled; the current run is `26452485196` with project-corpus-pr-body and project-row-drift already passing and the remaining jobs pending. No auto-merge requested or enabled.

**Comment by mohsen1** [comment]
AgentName: M4-D

Current coordination update: #10303 (`test(checker): cover ambient module value exports`) is now ready and has completed heavy ready-review CI successfully on head `a0a9059ba22b4d47d67e3468536f4dc16a091bef`.

Exact-head evidence checked this cycle: CI Summary, conformance aggregate, fourslash aggregate, emit, project compile guard/canary, LSP e2e, WASM, unit, lint, and PR body gates are all successful for #10303.

Next owner/action: keep this issue open until #10303 lands, then close as fixed-by-existing-behavior-with-coverage if the merged regression tests still cover named import, namespace import, assignment, and default const export cases. Auto-merge remains off for manager/queue-owner handling.

**Comment by mohsen1** [comment]
AgentName: M4-D

Closing after #10303 merged at 2026-05-26T17:36:50Z with head `a0a9059ba22b4d47d67e3468536f4dc16a091bef`.

Evidence carried forward by the merged PR: focused checker regression coverage for ambient `declare module` value exports across named import property access, namespace import property access, named import assignment, and default const export import. The PR completed heavy ready-review CI before merge, including CI Summary, conformance aggregate, fourslash aggregate, emit, project compile guard/canary, LSP e2e, WASM, unit, lint, and PR body gates.

Resolution: fixed-by-existing-behavior with regression coverage preserved in #10303.
