### ISSUE TITLE
declaration-mode overload-vs-impl compat FP on deeply-recursive Chainable/SelectP (ts-pattern)

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#15726]
## Summary

Under `declaration: true`, tsz emits two false positives on the ts-pattern fixture that `tsc` (6.0-dev) does not:

- `../tsz-canary-fixtures/ts-pattern/src/patterns.ts(673,17): error TS2394: This overload signature is not compatible with its implementation signature.`
- `../tsz-canary-fixtures/ts-pattern/src/patterns.ts(805,14): error TS4023: Exported variable '_' has or is using name 'isVariadic' from external module "symbols" but cannot be named.`

Both are declaration-emit-path only. Under `--noEmit` neither appears.

## The canary row is NOT affected

The canary / compile-guard compiles ts-pattern with `tsz --noEmit -p tsconfig.tsz-guard.json` (`project-compile-guard.sh check_project`, driven by `project-compile-canary-aggregate.sh run_canary_projects`). Under that config the row is 0 diagnostics (matches tsc). TS2394/TS4023 surface only under the project's own `tsconfig.json` (`declaration: true`). TS4023 is a long-standing declaration-emit limitation ("cannot be named"), so the canary was not compiling with `declaration: true` even this morning when the row was green. This issue tracks the declaration-mode parity gap, which does not gate the green canary row.

Related: the ts-pattern TS2536 canary regression (a separate, `--noEmit`-visible FP introduced by #15709) is fixed in PR #15725.

## TS2394 — what is known

- Anchored at the second `select` overload (patterns.ts:673): a `const`-parameter overload whose return type is a conditional (`patternOrKey extends string ? Chainable<SelectP<patternOrKey, ...>> : Chainable<SelectP<anonymousSelectKey, input, patternOrKey>, ...>`), checked against the impl return `Chainable<SelectP<string>, ...>`.
- The overload-vs-implementation compatibility checker (`crates/tsz-checker/src/state/state_checking_members/overload_compatibility.rs`) is unchanged in the recent batch, so this is a downstream type-evaluation effect, and it only manifests through the declaration-emit path.
- `SelectP<...> = Matcher<...>` and `Chainable` is a deeply self-recursive method intersection, so the impl/overload return relation walks a large recursive graph.
- **#15680 is NOT the cause.** I reverted its `subtype_of_conditional_target` fail-fast change in `crates/tsz-solver/src/relations/subtype/rules/conditionals.rs` and rebuilt; TS2394 was unchanged. (I had initially suspected it because the overload return is a conditional type; ruled out by experiment.)
- Not yet reproduced in isolation — a hand-built repro with a simplified (non-recursive) `Chainable` stays clean in both tsz and tsc; the recursion and/or declaration-emit re-check appear load-bearing.

## Repro

```
tsz --noEmit -p ../tsz-canary-fixtures/ts-pattern/tsconfig.json   # declaration:true -> TS2394 + TS4023
tsz --noEmit -p ../tsz-canary-fixtures/ts-pattern/tsconfig.tsz-guard.json  # noEmit -> clean
tsc  --noEmit -p ../tsz-canary-fixtures/ts-pattern/tsconfig.json   # clean (0)
```

## Suggested next steps

- Determine why the FP is declaration-mode-only (does the declaration-emit path re-run overload/impl compat, or resolve the erased conditional return `any extends string ? A : B` differently than `--noEmit`?).
- Bisect the remaining today-batch solver/checker changes under `declaration: true` (e.g. #15722 return-inference), or confirm it predates the batch.
- Confirm TS4023 provenance separately (likely long-standing declaration-emit "cannot be named" gap).
