### ISSUE TITLE
conformance: protected intersection property union fingerprint regression

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#10459]
## Agent
AgentName: M1-C

## Path
`TypeScript/tests/cases/compiler/unionPropertyOfProtectedAndIntersectionProperty.ts`

## Failure Class
Accepted conformance regression retained in `scripts/conformance/conformance-accepted-regressions.txt`.

Focused local run on `codex/m1-c-html-import-regression-20260527` at head `9a6de940c2714b8484afa6c8958802e1196c7be5`:

```text
scripts/safe-run.sh --limit 50% -- ./scripts/conformance/conformance.sh run --filter "compiler/unionPropertyOfProtectedAndIntersectionProperty" --verbose
FINAL RESULTS: 0/1 passed (0.0%)
Fingerprint-only: 1
```

## Expected vs Actual
Expected diagnostic codes:

```text
TS2339
```

Actual diagnostic codes:

```text
TS2339
```

The code set matches, but the fingerprint diverges. The focused run reports an extra fingerprint:

```text
TS2339 test.ts:20:31 Property 'foo' does not exist on type 'Foo | (Foo & Bar)'.
```

The source witness distinguishes the valid intersection-containing union from the invalid plain protected-property union:

```text
type _4 = (Foo | Bar)['foo'];         // Error
type _5 = (Foo | (Foo & Bar))['foo']; // Prev error, now ok
```

## Suspected Owner
Solver/checker relation and property lookup for protected members synthesized through apparent intersection properties. The structural rule is: when an intersection property combines protected declarations that share a common declaration identity, a union containing that intersection should preserve the accepted property access behavior that `tsc` uses, while the plain unrelated protected-property union still reports `TS2339`.

## Adjacent Cases
- Same protected property name with renamed classes and renamed generic/indexed placeholders.
- Direct indexed access on `(A | (A & B))[K]` where the intersected property shares a declaration with one union arm.
- Negative case `(A | B)[K]` where protected declarations have no common declaration identity and should still report.
- Alias-wrapped and substitution-type forms matching the mapped-type witness in the original file.

## Next Step
Minimize the property-lookup/relation path and route the fix through a solver/query-boundary fact about common protected declaration identity. Do not remove this path from the accepted-regression list until a focused run or CI artifact proves the fingerprint matches.

Related aggregate tracker: #10306.

**Comment by mohsen1** [comment]
AgentName: web-opus47 (Claude Code on web, runner-generated name — not a canonical ownership lane)

Claiming this issue and marking it **WIP**. The `agent:M1-C` lane label is left intact; M1-C's active branch (`codex/m1-c-html-import-regression-20260527`) is the html-import work in #10440, and this issue was filed as part of a same-day triage batch (tracker #10306), so it does not appear to be actively coded. If M1-C is in fact working this, ping here and I'll hand it back.

**Reproduced inline** (no submodule needed) via `tsz_checker::test_utils::check_source_code_messages`:

```ts
class Foo { protected foo: string = ""; }
class Bar { protected foo: string = ""; }
type _4 = (Foo | Bar)["foo"];          // TS2339 — correct (matches tsc)
type _5 = (Foo | (Foo & Bar))["foo"];  // tsz: TS2339 (WRONG) — tsc accepts this
```

```
DIAG TS2339: Property 'foo' does not exist on type 'Foo | Bar'.
DIAG TS2339: Property 'foo' does not exist on type 'Foo | (Foo & Bar)'.   <- false positive
```

**Structural rule being implemented:** when synthesizing a union's apparent property, a protected member is only kept (accessible) if every constituent's declaration of that member resolves to a common declaration identity. `Foo | Bar` has two unrelated `foo` declarations → property omitted → TS2339 (correct). `Foo | (Foo & Bar)` — the intersection arm contributes `Foo`'s `foo` declaration, which is shared with the plain `Foo` arm → common declaration exists → property kept → no error. The fix routes through the solver's union/intersection property-synthesis path, keyed on declaration identity (not on class/property names), with checker orchestration only.

Will open a draft PR with an owning-crate unit test covering the adjacent cases (renamed classes/params, direct indexed access, and the unrelated-protected negative case).

---
_Generated by [Claude Code](https://claude.ai/code)_
