### ISSUE TITLE
diagnostic-divergence(solver): fresh object-literal excess-property check (TS2353) suppressed -> wrong TS2345 when target's only property is an Object.prototype/Function member (`length`, `toString`, `valueOf`, ...)

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#14849]
## Summary
When a fresh object literal is passed/assigned to an object type whose only property is a member of the global `Object`/`Function` apparent type, tsz reports the whole-object **TS2345** relation failure instead of the property-level excess **TS2353** that tsc reports. The trigger set is exactly `toString`, `valueOf`, `constructor`, `toLocaleString`, `hasOwnProperty`, `isPrototypeOf`, `propertyIsEnumerable`, and `length`. Any other single property name (e.g. `id`, `name`, `push`, `charAt`) — or adding a second non-apparent property — produces the correct TS2353. The divergence affects both the diagnostic CODE (2345 vs 2353) and the SPAN (whole-argument vs the offending property). Reachable on the JSDoc axis via `@type {{ length: number }}` / `@template {{ length: number }} T` / `@param`.

## Repro (input + flags)
Flags: `--strict --target es2022 --lib es2022 --noEmit`
```ts
// f2.ts
declare function g(x: { length: number }): void;
g({ length: 1, zzz: 3 });
```
JSDoc-axis variant (`--allowJs --checkJs`):
```js
/**
 * @template {{ length: number }} T
 * @param {T} x
 */
function g(x) {}
g({ zzz: 3 });
```

## tsz vs tsc 5.9.3 (verbatim)
```
--- tsz ---
f2.ts(2,3): error TS2345: Argument of type '{ length: number; zzz: number; }' is not assignable to parameter of type '{ length: number; }'.
--- tsc ---
f2.ts(2,16): error TS2353: Object literal may only specify known properties, and 'zzz' does not exist in type '{ length: number; }'.
```
Discriminator map (target `{ P: number }`, arg `{ P: 1, zzz: 3 }`, non-generic):
```
length               -> tsz=TS2345  tsc=TS2353
toString             -> tsz=TS2345  tsc=TS2353
valueOf              -> tsz=TS2345  tsc=TS2353
hasOwnProperty       -> tsz=TS2345  tsc=TS2353
constructor          -> tsz=TS2345  tsc=TS2353
toLocaleString       -> tsz=TS2345  tsc=TS2353
isPrototypeOf        -> tsz=TS2345  tsc=TS2353
propertyIsEnumerable -> tsz=TS2345  tsc=TS2353
id / name / push / charAt -> tsz=TS2353 tsc=TS2353 (correct)
```
Controls: with a second non-apparent property (`{ length: number; foo: string }`) tsz correctly emits TS2353; via a variable (`const o = { length: 1, zzz: 3 }; g(o)`) both compilers accept it (so the underlying subtype relation is fine — the bug is on the fresh-literal excess path).

## Root cause (wrong op + tsz file:line)
Wrong operation: fresh-object-literal excess-property elaboration bypassed by an apparent-type/weak-type shortcut. The hardcoded Object.prototype/string member list in `crates/tsz-solver/src/relations/compat_weak.rs:306-309` (`"toString" | "valueOf" | "constructor" | "toLocaleString" | "hasOwnProperty" | "isPrototypeOf" | "propertyIsEnumerable"`, plus `length` in the string-like branch around :539) exactly matches the observed trigger set. When the target's sole property is one of these, the relation treats it as satisfied-by-apparent-type and returns a generic mismatch; the checker-side excess elaboration (`crates/tsz-checker/src/types/computation/call_finalize.rs`, which calls `check_object_literal_excess_properties` -> TS2353) is never reached, so TS2345 is emitted at the argument span.

## Path to fixing
The weak-type / apparent-overlap shortcut must not absorb a property of a FRESH object literal: excess-property checking takes precedence over the Object.prototype-member overlap heuristic. Gate the `compat_weak.rs` short-circuit so it does not apply when the source is a fresh object literal (so the call/assignment path still runs `check_object_literal_excess_properties` and yields TS2353). Alternatively, run the fresh-literal excess elaboration before consulting the weak/apparent-overlap path. Add tests for single-property `{ length: number }` / `{ toString: ... }` targets with a fresh excess literal (positive: TS2353) and the variable (non-fresh) negative control, plus renamed-property variants to keep it structural.

## Adjacent cases
- Generic constraint form `T extends { length: number }` exhibits the same divergence (related to CLOSED #9728, which fixed the generic-constraint excess path for NON-apparent property names like `id`; the apparent-member subset was never covered).
- JSDoc `@type {{ length: number }}` / `@param {{ length: number }}` / `@template` constrained forms in checked JS all hit it.
- `length: string` (wrong-typed) also triggers TS2345, confirming the trigger is the property NAME, not its type.

Goal: hold

## Provenance
Machine: m1
Assistant: claude-code
Model: claude-opus-4-8
Effort: high

## Verification
Machine: m1 · Assistant: claude-code · Model: claude-opus-4-8 · M1FableArchitect
Root cause verified: the apparent/weak-member name list at `crates/tsz-solver/src/relations/compat_weak.rs:306-309` (and `length` near :539) matches the observed trigger set exactly. Verifiable by `tsz --strict --noEmit f2.ts` (expect TS2353 at the offending property span) vs the `id`/`name` controls that already emit TS2353.
