### ISSUE TITLE
regression(checker): `NS.Nope` through a named import of `export * as NS` now emits TS2702 instead of TS2694 — red on main since tonight's TS2694 family merges

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#17197]
Found while verifying #17195's family sweep: `cargo test -p tsz-checker --test export_star_as_named_import_type_anchor_tests` is red on pristine main `fa7160c` (verified with a fully clean tree — this is NOT caused by #17195, whose diff was reverted for the check; still red either way).

Failing test: `missing_member_through_export_star_as_namespace_anchor_emits_2694` (`crates/tsz-checker/tests/export_star_as_named_import_type_anchor_tests.rs`, the #14228 coverage).

## Repro

```
g/globals.ts:  export interface Foo { a: number }
               export type Bar = { b: string };
g/index.ts:    export * as NS from './globals';
consumer.ts:   import { NS } from './g/index';
               type T = NS.Nope;
```

- tsc 7.0.2 (oracle, verified tonight): `consumer.ts(2,13): error TS2694: Namespace '".../g/globals"' has no exported member 'Nope'.`
- tsz main `fa7160c`: `TS2702: 'NS' only refers to a type, but is being used as a namespace here.` — wrong code AND wrong blame; the anchor namespace itself stopped resolving as a namespace.

Note this is a **plain qualified type reference** (`NS.Nope`), not an import-type — the `export * as NS` named-import anchor path regressed, not the `import("...")` resolver.

## Where it came from

Not bisected yet. The window is tonight's TS2694-family merges up to `fa7160c`: #17182 (`2807445`), #17183 (`0409830`), #17184, #17188 (`9bb95c4`) — all touch import-type/JSDoc resolution; the TS2702 symptom suggests whatever now classifies the `export * as NS` re-export binding lost its namespace meaning on this path. The oracle expectation of the red test is confirmed correct, so this is a compiler regression, not a wrong test (checked per the board's oracle-first rule).

## Next concrete action

Bisect the four merge points above with:
```
cargo test -p tsz-checker --test export_star_as_named_import_type_anchor_tests
```
(builds in ~2-3 min per point on a cloud seat; the other 5 tests in the target pass, so the failure is precise). Then fix at the owning layer — the named-import-of-`export * as` namespace-anchor resolution — not by relaxing the test.

---
Machine: cloud / Assistant: claude-code / Model: claude-fable-5 / Effort: medium / AgentName: Wozniak
