### ISSUE TITLE
fix(parser): parserSymbolIndexer5 conformance regression — missing TS1005 ':' expected (from #10701)

### ISSUE THREAD

**Issue by mohsen1** [mohsen1/tsz#11456]
## Summary
`parserSymbolIndexer5` conformance regressed on `main` (fingerprint-only): tsz no longer emits the trailing `TS1005: ':' expected` diagnostic that `tsc` produces. This trips `conformance-aggregate` (unlisted regression) on PRs branched from current `main`.

## Repro
Test: `TypeScript/tests/cases/conformance/parser/ecmascript6/Symbols/parserSymbolIndexer5.ts`
Effective source (after stripping `//@target: ES6`):
```ts
var x = {
    [s: symbol]: ""
}
```

Local runner (current main):
```
.target/dist-fast/tsz-conformance --filter parserSymbolIndexer5 --verbose --workers 1 \
  --cache-file scripts/conformance/tsc-cache-full.json
=> Fingerprint-only failures (1):
   TS1005 test.ts:3:1 ':' expected. (missing=1, extra=0)
```

## Expected vs actual
tsc expects 6 diagnostics; tsz matches all error codes EXCEPT it is **missing** `parserSymbolIndexer5.ts(3,1): error TS1005: ':' expected.` (position = the closing `}`).

## Root cause
Introduced by #10701 (`fix(parser): recover object private indexer emit tail`, commit b090424382). The new `recover_object_literal_computed_indexer_tail` in `crates/tsz-parser/src/parser/state_expressions_literals.rs` consumes the `: <expr>` tail and builds a comma BinaryExpression, exiting the object-member list cleanly — which suppresses the `':' expected` diagnostic `tsc` still reports at the `}`.

## Impact
Blocks `conformance-aggregate` (and thus the merge queue's synthetic-merge gate) for PRs off current `main`.

## Fix in progress
A targeted parser fix is being prepared (branch `codex/fix-parsersymbolindexer5-recovery-20260528`) to restore the trailing `':' expected` diagnostic while preserving #10701's `object_literal_private_indexer_tail_recovers_as_comma_initializer` behavior.

AgentName: opus48-emit100

**Comment by mohsen1** [comment]
Validation note: I reviewed this issue and validated the report shape.

- Current TS target in tsz is scripts/conformance/typescript-versions.json -> 6.0.3, so the comparison point should be TS 6 behavior.
- Case family: unknown.
- Boundary: not specified, target surface: unknown.
- File/module hint: not specified.
- This issue appears structurally valid and includes enough context for triage.
- Next validation step: reproduce under TS 6.0.3 (tsc + tsz harness for this fixture) and attach concrete divergence before assigning priority.
- If this is now fixed on TS 6.0.3 behavior, post evidence and close as resolved.
Related issue family: fix(parser).
